DEFAULT_COUNT_MOVIES_ON_PAGE = 50

DEFAULT_CHARFIELD_MAX_LENGTH = 256
DEFAULT_EMAILFIELD_MAX_LENGTH = 150
DEFAULT_TEXTFIELD_MAX_LENGTH = 980

MIN_CREATED_MOVIE_YEAR = 1900
MAX_CREATED_MOVIE_YEAR = 2025
